[package]
name = "blockstore"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
cid = { version = "0.11.1", features = ["alloc"] }
multihash = "0.19.3"
sha2 = "0.10.9"
rand = "0.9.2"
tempfile = "3.23.0"

